#!/bin/bash

# Install apache
yum -y install httpd-2.4.46

# Set up proxy for Tomcat server
cat <<EOT >> /etc/httpd/conf/httpd.conf
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ProxyRequests Off
ProxyPass / http://localhost:8080/
ProxyPassReverse / http://localhost:8080/

<Location "/">
  Order allow,deny
  Allow from all
</Location>
EOT
